-- AlterEnum
ALTER TYPE "NotifType" ADD VALUE 'NEW_MESSAGE';
ALTER TYPE "NotifType" ADD VALUE 'EVENT_CREATED';
ALTER TYPE "NotifType" ADD VALUE 'EVENT_UPDATED';
ALTER TYPE "NotifType" ADD VALUE 'EVENT_CANCELLED';
ALTER TYPE "NotifType" ADD VALUE 'JOB_UPDATED';
ALTER TYPE "NotifType" ADD VALUE 'NEW_STORY';
ALTER TYPE "NotifType" ADD VALUE 'SYSTEM';
