-- AlterEnum
ALTER TYPE "NotifType" ADD VALUE IF NOT EXISTS 'NEW_MESSAGE';
ALTER TYPE "NotifType" ADD VALUE IF NOT EXISTS 'EVENT_CREATED';
ALTER TYPE "NotifType" ADD VALUE IF NOT EXISTS 'EVENT_UPDATED';
ALTER TYPE "NotifType" ADD VALUE IF NOT EXISTS 'EVENT_CANCELLED';
ALTER TYPE "NotifType" ADD VALUE IF NOT EXISTS 'JOB_UPDATED';
ALTER TYPE "NotifType" ADD VALUE IF NOT EXISTS 'NEW_STORY';
ALTER TYPE "NotifType" ADD VALUE IF NOT EXISTS 'SYSTEM';

